// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLe8jvrgzmv-vLbcgdGBIfLukFfkw8N3g',
    appId: '1:719249224018:web:e61b4294d09b3b0cd50a8b',
    messagingSenderId: '719249224018',
    projectId: 'project-ed045',
    authDomain: 'project-ed045.firebaseapp.com',
    storageBucket: 'project-ed045.appspot.com',
    measurementId: 'G-2KVTRLSW8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg1zlqA11ChOevr0reypeYPfUA-9B7J-w',
    appId: '1:719249224018:android:05f49cbd90d1856bd50a8b',
    messagingSenderId: '719249224018',
    projectId: 'project-ed045',
    storageBucket: 'project-ed045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAph_kyhUyLkIOMqMD_hUYOFayWDp6GQkg',
    appId: '1:719249224018:ios:59859ed1f503b126d50a8b',
    messagingSenderId: '719249224018',
    projectId: 'project-ed045',
    storageBucket: 'project-ed045.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
